global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus_investorhub:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter_investorhub:9100']

  - job_name: 'nestjs-app'
    static_configs:
      - targets: ['nestjs_app_investorhub:3000']
    metrics_path: '/metrics'

  - job_name: 'nestjs-clock'
    static_configs:
      - targets: ['nestjs_app_investorhub_clock:3000']
    metrics_path: '/metrics'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis_server_investorhub:6379']
    metrics_path: '/metrics' 