---

app:
  blockchain:
    nodes:
      -
        url: ${INFURA_URL}
        apiKey: ${INFURA_API_KEY}
        pools:
            - ${POOL_CONTRACT_ADDRESS_UNISWAP_V2}
            - ${POOL_CONTRACT_ADDRESS_UNISWAP_V3}