---

app:
  blockchain:
    nodes:
      -
        url: ${INFURA_URL}
        apiKey: ${INFURA_API_KEY}
        pools:
          - address: ${POOL_CONTRACT_ADDRESS_UNISWAP_V2}
            topics:
              - ${POOL_TOPIC_PAIR_CREATED_UNISWAP_V2}
          - address: ${POOL_CONTRACT_ADDRESS_UNISWAP_V3}
            topics:
              - ${POOL_TOPIC_POOL_CREATED_UNISWAP_V3}
