server:
  port: 7700
  shutdown: graceful
  http2:
    enabled: true

spring:
  application:
    name: staking-aggregator-service
  config:
    import:
      - classpath:app.yml
      - optional:file:./environments.properties
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    property-naming-strategy: SNAKE_CASE
  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true
  task:
    execution:
      thread-name-prefix: staking-aggregator-task-
      pool:
        core-size: 4
        max-size: 80
        queue-capacity: 10_000
    scheduling:
      thread-name-prefix: staking-aggregator-scheduling-
      pool:
        size: 10
#  docker:
#    compose:
#      lifecycle-management: start-only

management:
  endpoint:
    info:
      enabled: true

error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR

springdoc:
  pathsToMatch: /

logging:
  level:
    org:
      web3j:
        protocol: INFO
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
    root: INFO