services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - NODE_ENV=production

  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"