services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nestjs_app
    command: pnpm run start:dev
    environment:
      - NODE_ENV=development
    develop:
      watch:
        # Sincroniza alterações no código fonte
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
            - dist/
        # Reinicia o serviço se arquivos críticos mudarem (como .env ou config)
        - action: sync+restart
          path: .env
          target: /app/.env