services:
  staking-aggregator-service-mongodb:
    image: mongo:8.0.4
    environment:
    - MONGO_INITDB_DATABASE=staking-aggregator-service
    - MONGO_INITDB_ROOT_USERNAME=staking-aggregator-service
    - MONGO_INITDB_ROOT_PASSWORD=$t@k1nG
    command:
    - --replSet
    - rs0
    - --bind_ip_all
    ports:
    - 27018:27017
    volumes:
    - sas-mongodb:/data/db/
    healthcheck:
      test: test $$(mongosh --quiet --eval "try {rs.initiate({_id:'rs0',members:[{_id:0,host:\"mongodb:27017\"}]})}
        catch(e) {rs.status().ok}") -eq 1
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  sas-mongodb: